{% set name = "galaxy-tool-util-models" %}
{% set version = "26.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/galaxy_tool_util_models-{{ version }}.tar.gz
  sha256: 5cf256c0f3732c589f8658a6edc9ef39203952bcb621297f851a205a936528ab

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - pydantic >=2.7.4
    - python >={{ python_min }}
    - typing_extensions

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - galaxy
    - galaxy.tool_util_models
  commands:
    - pip check

about:
  home: https://galaxyproject.org
  summary: Pydantic models for Galaxy tools
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nsoranzo
    - bgruening
