{% set name = "galaxy-tool-util-models" %}
{% set version = "26.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/galaxy_tool_util_models-{{ version }}.tar.gz
  sha256: d7cbcec52f764dc046d8b10fa9f49a901bfc2bcb8490e5554c0fa5dfa38b10f0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - pydantic >=2.7.4
    - python >={{ python_min }}
    - typing_extensions

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - galaxy
    - galaxy.tool_util_models
  commands:
    - pip check

about:
  home: https://galaxyproject.org
  summary: Pydantic models for Galaxy tools
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nsoranzo
    - bgruening
