{% set name = "galaxy-tool-util-models" %}
{% set version = "25.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/galaxy_tool_util_models-{{ version }}.tar.gz
  sha256: 65d6d7f75eb473b8f1865473cac1b720734c0b67036af922f8bd226aee358406

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - pydantic !=2.6.0,!=2.6.1,>=2
    - python >={{ python_min }}
    - typing_extensions

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - galaxy
    - galaxy.tool_util_models
  commands:
    - pip check

about:
  home: https://galaxyproject.org
  summary: Pydantic models for Galaxy tools
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nsoranzo
    - bgruening
